# Basic Information 
title: Difang Huang
position: Assistant Professor
affiliation: Chinese Academy of Sciences
email: difang (at) amss.ac.cn

# Search Engine Optimization (SEO)
keywords: difang huang, huang difang, difanghuang, huangdifang

# Links 
google_scholar: https://scholar.google.com/citations?user=CZ61snQAAAAJ&hl=en&oi=ao
ssrn: https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=3911606 
arxiv: https://arxiv.org/a/huang_d_1.html 


# Images
avatar: ./assets/img/avatar.jpg

# Footnote
enable_footnote: false

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Serif"

# Google Analytics ID
google_analytics:

# Use this project as a remote theme for GitHub Pages
remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
